### PR TITLE
add ability to choose if we want to reload attens or not. 

### PR DESCRIPTION
**Pull request by kmharrington**
solves #262

### CODE REVIEW

**Review by jlashner — COMMENTED** [review]
Looks good to me, but I think if `modify_attens` is True, and there are atten values saved in the device config, it makes sense to me for uxm_setup to set attens to whatever's in the device cfg instead of just leaving it.

**Comment by kmharrington** [comment]
you mean if modify_attens is False? 

If True --> run attenuation optimization. If False --> load from config file.

**Comment by kmharrington** [comment]
@jlashner  I think this is what you're looking for?

**Comment by jlashner** [comment]
I think how this is implemented it'll change the attens to the dev-config values if `modify_attens` is False. One sec... about to commit somethingg

**Comment by jlashner** [comment]
@kmharrington can you check that commit and see if you agree?

**Comment by dpdutcher** [comment]
I think there are different understandings of "modify_attens":
1. In one sense, apply possibly different attens to whatever the smurf board is currently using, but that could match the device config. (modify what is currently in use).
2. In the other sense, do not just use the settings from the config file, find appropriate ones from scratch again (modify what is in the config file).

**Comment by kmharrington** [comment]
Yeah Daniel, you called the confusion. At LATR we want a kwarg that will force the re-estimation of the attenuation

**Comment by kmharrington** [comment]
So, sounds like we want two kwargs? maybe `force_estimate_attens` and `load_config_attens`?

**Comment by dpdutcher** [comment]
I like the version as of https://github.com/simonsobs/sodetlib/pull/270/commits/598060a6eef1f1430d35fc5f02f1327c9d069fd8
> I think how this is implemented it'll change the attens to the dev-config values if modify_attens is False.
What would the attens be set to if not what's in the dev-config? (okay, technically what's in the pysmurf config file, but no one looks at that). This is uxm_setup after all, first time set up, so it doesn't really matter what's on the board, right?

**Comment by jlashner** [comment]
If you've done work to set attens manually and trust whatever attens are already loaded into the smurf then you may want to run uxm_setup without touching the already loaded values. Probably not from the pysmurf-config, but from general operation and interactive debugging. I've definitely been in that situation

**Comment by jlashner** [comment]
I support second kwarg to force estimate attens, and think `modify_attens=False` should mean don't touch currently loaded values

**Comment by jlashner** [comment]
But also we should update the docstrings to reflect whatever our choice is

**Comment by jlashner** [comment]
Reviewing this thread and now I'm agreeing more with Katie's definition of what `modify_attens` should mean. I reverted back to Katie's commit and added some clarification in the docs.

**Review by jlashner — APPROVED** [review]

**Pull request merged**
