### PR TITLE
Update bias_dets.py

### PR DESCRIPTION
**Pull request by dpdutcher**
In biasstep_rebias: it should be `cfg.dev.exp`, not `cfg.dev.experiment`

### CODE REVIEW

**Comment by msilvafe** [comment]
I'm a bit confused why you needed this change. The device config code loads everything in the `experiment` section of the dev_cfg yaml into `cfg.exp`: https://github.com/simonsobs/sodetlib/blob/514b8b16042ab10496639b89d4fb98154cfa7495/sodetlib/det_config.py#L114-L172

**Comment by dpdutcher** [comment]
cfg.dev does not have an "experiment" attribute, it only has a "exp" attribute. 
So `sleep_time = cfg.dev.experiment["overbias_sleep_time_sec"]` fails with an attribute error.

**Comment by msilvafe** [comment]
> cfg.dev does not have an "experiment" attribute, it only has a "exp" attribute. 
> 
> So `sleep_time = cfg.dev.experiment["overbias_sleep_time_sec"]` fails with an attribute error.

Ahh ok I read this wrong I thought you were changing exp -> experiment not the other way around.

**Review by msilvafe — APPROVED** [review]
Thanks for testing and catching this.

**Pull request merged**
